// 'use client';
import '../assets/scss/globals.scss';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faEnvelope, faPhone, faLocationDot } from '@fortawesome/free-solid-svg-icons';
import { faFacebook, faGithub, faLinkedin, faTelegram, faTwitter } from '@fortawesome/free-brands-svg-icons'

import Link from 'next/link';

import localFont from 'next/font/local';

import Script from 'next/script'

export const metadata = {
  title: 'Hiren Chhatbar',
  description: 'Generated by create next app',
}

const logoFont = localFont({ src: '../public/fonts/pacifico-regular.ttf' });

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="light">
      <body>
        <header>
          <div className="d-flex justify-content-around align-items-center">
            <nav className='navbar navbar-expand-lg container-fluid py-2 shadow'>
              <div className='container-fluid px-2 px-sm-4 px-xl-5 px-md-5 px-lg-5'>
                <Link href="/" className={`navbar-brand ${logoFont.className}`}>Hiren Chhatbar</Link>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Toggle navigation">
                  <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="menu">
                  <ul className="navbar-nav ms-auto gap-3">
                    <li className="nav-item">
                      <Link href="/" className="nav-link">
                        Home
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link href="/about" className="nav-link">
                        About
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link href="/experience" className="nav-link">
                        Experience
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link href="/portfolio" className="nav-link">
                        Portfolio
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link href="/contact" className="nav-link">
                        Contact
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </header>

        {children}

        <footer className='text-lg-start pt-5 pb-4' >
          <div className='container text-md-start'>
            <div className='row text-start text-md-left'>
              <div className="col-md-3 col-lg-3 col-xl-3 mx-auto">
                <Link href='/' className={`mb-4 ${logoFont.className}`}>Hiren Chhatbar</Link>
                <p className='mt-2'>
                  Thank you for visiting my personal portfolio website. Connect with me over socials.
                </p>
              </div>

              <div className="col-md-3 col-lg-2 col-xl-2 mx-auto mb-2">
                <h5 className='text-uppercase mb-3'>Useful links</h5>
                <p>
                  <Link href='/'>
                    Home
                  </Link>
                </p>
                <p>
                  <Link href='/about'>
                    About
                  </Link>
                </p>
                <p>
                  <Link href='/experience'>
                    Experience
                  </Link>
                </p>
                <p>
                  <Link href='/portfolio'>
                    Portfolio
                  </Link>
                </p>
                <p>
                  <Link href='/contact'>
                    Contact
                  </Link>
                </p>
              </div>

              <div className="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <h5 className='text-uppercase mb-3'>Contact</h5>
                <Link href="+01 234 567 88"><p>
                  <FontAwesomeIcon icon={faPhone} width={25} height={25} className="me-3" />+01 234 567 88</p>
                </Link>
                <Link href="mailto:info@example.com"><p>
                  <FontAwesomeIcon icon={faEnvelope} width={25} height={25} className="me-3" />
                  info@example.com</p>
                </Link>
                <p>
                  <FontAwesomeIcon icon={faLocationDot} width={25} height={25} className="me-3" />
                  New York, NY 10012, US
                </p>
                <div className='pt-4'>
                  <Link href='' className='me-2'>
                    <FontAwesomeIcon icon={faLinkedin} width={25} height={25} />
                  </Link>
                  <Link href='' className='me-2'>
                    <FontAwesomeIcon icon={faGithub} width={25} height={25} />
                  </Link>
                  <Link href="mailto:info@example.com" className='me-2'>
                    <FontAwesomeIcon icon={faEnvelope} width={25} height={25} />
                  </Link>
                  <Link href='' className='me-2'>
                    <FontAwesomeIcon icon={faTwitter} width={25} height={25} />
                  </Link>
                  <Link href='' className='me-2'>
                    <FontAwesomeIcon icon={faTelegram} width={25} height={25} />
                  </Link>
                  <Link href='' className='me-2'>
                    <FontAwesomeIcon icon={faFacebook} width={25} height={25} />
                  </Link>
                </div>
              </div>
            </div>
          </div>

          <div className='p-3 border-top text-center'>
            <p>Copyright © 2023
              <Link className={`mx-1 ${logoFont.className}`} href='/'>
                Hiren Chhatbar
              </Link>
              All rights reserved.
            </p>
          </div>
        </footer>
      </body>
      <Script src="/bootstrap.bundle.min.js" />
    </html>
  )
}